/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";
import React, { useRef } from "react";
import { useGLTF, Stage, PresentationControls } from "@react-three/drei";
// import { useFrame } from "@react-three/fiber";
// import { Canvas } from '@react-three/fiber'
import {
    ContactShadows,
    Environment,
    PerspectiveCamera,
} from "@react-three/drei";
import { Canvas } from "@react-three/fiber";
import { extend } from '@react-three/fiber'
import { OrbitControls, TransformControls } from 'three-stdlib'
// extend({ OrbitControls, TransformControls, Canvas })
export default function Robot(props) {
    const { nodes, materials } = useGLTF('/models/Warrior_Robot_2.glb')
    return (
        // <group {...props} dispose={null}>
        <mesh
            {...props}
            castShadow
            receiveShadow
            geometry={nodes.mesh_0.geometry}
            material={nodes.mesh_0.material}
            scale={[2, 2, 2]}
        />
        // </group>
    )
}
function Model(props) {
    const { scene } = useGLTF("/models/Warrior_Robot_1.glb");
    return <primitive object={scene} {...props} />
}

export function RobotCanvas() {
    return (
        <>

            <Model scale={0.008} />
        </>
    );
};



useGLTF.preload('/models/Warrior_Robot_2.glb')
