/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const BookModel = React.memo(function BookModel(props) {
  // Use React.memo for performance optimization
  const { nodes, materials } = useGLTF("/models/book.glb");

  const modelRef = useRef();

  useFrame(() => {
    modelRef.current.rotation.y += 0.007;
  });
  return (
    <group
      {...props}
      dispose={null}
      ref={modelRef}
      scale={[1.8, 1.8, 1.8]}
      rotation={[0.4, -1, 0]}
      position={[0, 8, 0]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_0.geometry}
        material={nodes.mesh_0.material}
        position={[0, -3.867, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[2, 2, 2]}
      />
    </group>
  );
});

export default BookModel;
useGLTF.preload("/models/book.glb");
